"""Task 2.8 - hand-built HTML/inline-XBRL fixture tests for
src/parse/inline_xbrl.py. Every expected value is hand-specified, never
generated by calling the function under test. No network, no real
primary-document data required (that lives in the local_data-marked
section at the bottom)."""

from __future__ import annotations

from decimal import Decimal

import pytest

from src.parse.inline_xbrl import (
    InlineXbrlParseError,
    NumericNormalizationError,
    parse_xml,
    extract_contexts,
    extract_units,
    extract_inline_facts,
    resolve_continued_text,
    normalize_numeric,
    context_to_truth_contract_period,
)

_XHTML_HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ix="http://www.xbrl.org/2013/inlineXBRL"
      xmlns:xbrli="http://www.xbrl.org/2003/instance"
      xmlns:xbrldi="http://xbrl.org/2006/xbrldi"
      xmlns:us-gaap="http://fasb.org/us-gaap/2023"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<head><title>Fixture</title></head>
<body>
<ix:header>
<ix:resources>
{resources}
</ix:resources>
</ix:header>
{body}
</body>
</html>"""

_CONTEXT_INSTANT = """<xbrli:context id="c-instant">
  <xbrli:entity><xbrli:identifier scheme="http://www.sec.gov/CIK">0000000001</xbrli:identifier></xbrli:entity>
  <xbrli:period><xbrli:instant>2023-12-31</xbrli:instant></xbrli:period>
</xbrli:context>"""

_CONTEXT_DURATION = """<xbrli:context id="c-duration">
  <xbrli:entity><xbrli:identifier scheme="http://www.sec.gov/CIK">0000000001</xbrli:identifier></xbrli:entity>
  <xbrli:period><xbrli:startDate>2023-01-01</xbrli:startDate><xbrli:endDate>2023-12-31</xbrli:endDate></xbrli:period>
</xbrli:context>"""

_CONTEXT_QUARTER = """<xbrli:context id="c-quarter">
  <xbrli:entity><xbrli:identifier scheme="http://www.sec.gov/CIK">0000000001</xbrli:identifier></xbrli:entity>
  <xbrli:period><xbrli:startDate>2023-10-01</xbrli:startDate><xbrli:endDate>2023-12-31</xbrli:endDate></xbrli:period>
</xbrli:context>"""

_CONTEXT_DIMENSIONAL = """<xbrli:context id="c-dim">
  <xbrli:entity>
    <xbrli:identifier scheme="http://www.sec.gov/CIK">0000000001</xbrli:identifier>
    <xbrli:segment><xbrldi:explicitMember dimension="us-gaap:StatementEquityComponentsAxis">us-gaap:CommonStockMember</xbrldi:explicitMember></xbrli:segment>
  </xbrli:entity>
  <xbrli:period><xbrli:instant>2023-12-31</xbrli:instant></xbrli:period>
</xbrli:context>"""

_UNIT_USD = '<xbrli:unit id="usd"><xbrli:measure>iso4217:USD</xbrli:measure></xbrli:unit>'
_UNIT_SHARES = '<xbrli:unit id="shares"><xbrli:measure>xbrli:shares</xbrli:measure></xbrli:unit>'


def _build(resources: str, body: str) -> str:
    return _XHTML_HEADER.format(resources=resources, body=body)


def _write_and_parse(tmp_path, xml_text: str):
    path = tmp_path / "fixture.htm"
    path.write_text(xml_text, encoding="utf-8")
    return parse_xml(path)


# --------------------------------------------------------------- numeric normalization (Section 68)

def test_plain_integer():
    assert normalize_numeric(raw_text="1234", scale=None, sign=None, format_name=None) == Decimal("1234")


def test_comma_separated_number():
    assert normalize_numeric(raw_text="1,234,567", scale=None, sign=None, format_name="ixt:num-dot-decimal") == Decimal("1234567")


def test_decimal_number():
    assert normalize_numeric(raw_text="1,234.56", scale=None, sign=None, format_name="ixt:num-dot-decimal") == Decimal("1234.56")


def test_negative_sign():
    assert normalize_numeric(raw_text="500", scale=None, sign="-", format_name=None) == Decimal("-500")


def test_scale_applied():
    # displayed "1,875" with scale=3 -> 1,875,000 (Section 28's exact scenario)
    assert normalize_numeric(raw_text="1,875", scale="3", sign=None, format_name="ixt:num-dot-decimal") == Decimal("1875000")


def test_zero():
    assert normalize_numeric(raw_text="0", scale=None, sign=None, format_name=None) == Decimal("0")


def test_fixed_zero_format():
    assert normalize_numeric(raw_text="", scale="0", sign=None, format_name="ixt:fixed-zero") == Decimal("0")


def test_zerodash_format():
    assert normalize_numeric(raw_text="-", scale="0", sign=None, format_name="ixt:zerodash") == Decimal("0")


def test_numwordsen_small():
    assert normalize_numeric(raw_text="three", scale="0", sign=None, format_name="ixt-sec:numwordsen") == Decimal("3")


def test_numwordsen_compound():
    assert normalize_numeric(raw_text="forty-two", scale="0", sign=None, format_name="ixt-sec:numwordsen") == Decimal("42")


def test_numwordsen_thousand():
    assert normalize_numeric(raw_text="five thousand", scale="0", sign=None, format_name="ixt-sec:numwordsen") == Decimal("5000")


def test_numwordsen_zero_synonym():
    assert normalize_numeric(raw_text="none", scale="0", sign=None, format_name="ixt-sec:numwordsen") == Decimal("0")


def test_numwordsen_hundred_only():
    assert normalize_numeric(raw_text="three hundred", scale="0", sign=None, format_name="ixt-sec:numwordsen") == Decimal("300")


def test_numwordsen_hundred_plus_ones():
    # real failure found in the full 990-document run: "One hundred three"
    assert normalize_numeric(raw_text="One hundred three", scale="0", sign=None, format_name="ixt-sec:numwordsen") == Decimal("103")


def test_numwordsen_hundred_plus_ones_second_case():
    # real failure found in the full 990-document run: "three hundred two"
    assert normalize_numeric(raw_text="three hundred two", scale="0", sign=None, format_name="ixt-sec:numwordsen") == Decimal("302")


def test_numwordsen_billion():
    # real failures found in the full 990-document run: "one billion" (x2)
    assert normalize_numeric(raw_text="one billion", scale="0", sign=None, format_name="ixt-sec:numwordsen") == Decimal("1000000000")


def test_numwordsen_hundred_plus_compound_tens():
    assert normalize_numeric(raw_text="two hundred forty-two", scale="0", sign=None, format_name="ixt-sec:numwordsen") == Decimal("242")


def test_numwordsen_space_separated_tens_ones():
    # real failure found in the full 990-document run: "twenty three"
    # (space-separated, not hyphenated like "twenty-three")
    assert normalize_numeric(raw_text="twenty three", scale="0", sign=None, format_name="ixt-sec:numwordsen") == Decimal("23")


def test_numwordsen_hundred_plus_space_separated_tens_ones():
    # real failure found in the full 990-document run: "one hundred thirty three"
    assert normalize_numeric(raw_text="one hundred thirty three", scale="0", sign=None, format_name="ixt-sec:numwordsen") == Decimal("133")


def test_unrecognized_format_raises():
    with pytest.raises(NumericNormalizationError):
        normalize_numeric(raw_text="123", scale=None, sign=None, format_name="ixt:some-unknown-transform")


def test_empty_numeric_text_raises():
    with pytest.raises(NumericNormalizationError):
        normalize_numeric(raw_text="", scale=None, sign=None, format_name=None)


def test_unrecognized_sign_raises():
    with pytest.raises(NumericNormalizationError):
        normalize_numeric(raw_text="100", scale=None, sign="?", format_name=None)


def test_negative_and_scale_combined():
    assert normalize_numeric(raw_text="1,000", scale="2", sign="-", format_name="ixt:num-dot-decimal") == Decimal("-100000")


# --------------------------------------------------------------- contexts / units

def test_instant_context(tmp_path):
    xml = _build(_CONTEXT_INSTANT + _UNIT_USD, "<p>body</p>")
    root = _write_and_parse(tmp_path, xml)
    contexts = extract_contexts(root)
    c = contexts["c-instant"]
    assert c.period.period_type == "instant"
    assert c.period.instant == "2023-12-31"
    assert c.dimensions == ()


def test_duration_context(tmp_path):
    xml = _build(_CONTEXT_DURATION + _UNIT_USD, "<p>body</p>")
    root = _write_and_parse(tmp_path, xml)
    c = extract_contexts(root)["c-duration"]
    assert c.period.period_type == "duration"
    assert c.period.start_date == "2023-01-01"
    assert c.period.end_date == "2023-12-31"


def test_dimensional_context_preserves_dimensions(tmp_path):
    xml = _build(_CONTEXT_DIMENSIONAL + _UNIT_USD, "<p>body</p>")
    root = _write_and_parse(tmp_path, xml)
    c = extract_contexts(root)["c-dim"]
    assert c.dimensions == (("us-gaap:StatementEquityComponentsAxis", "us-gaap:CommonStockMember"),)


def test_multiple_units(tmp_path):
    xml = _build(_UNIT_USD + _UNIT_SHARES + _CONTEXT_INSTANT, "<p>body</p>")
    root = _write_and_parse(tmp_path, xml)
    units = extract_units(root)
    assert units["usd"].measures == ("iso4217:USD",)
    assert units["shares"].measures == ("xbrli:shares",)


_UNIT_USD_PER_SHARE = """<xbrli:unit id="usdPerShare">
  <xbrli:divide>
    <xbrli:unitNumerator><xbrli:measure>iso4217:USD</xbrli:measure></xbrli:unitNumerator>
    <xbrli:unitDenominator><xbrli:measure>xbrli:shares</xbrli:measure></xbrli:unitDenominator>
  </xbrli:divide>
</xbrli:unit>"""


def test_divide_unit_extraction(tmp_path):
    xml = _build(_UNIT_USD_PER_SHARE + _CONTEXT_INSTANT, "<p>body</p>")
    root = _write_and_parse(tmp_path, xml)
    units = extract_units(root)
    u = units["usdPerShare"]
    assert u.measures == ()
    assert u.divide_numerator == ("iso4217:USD",)
    assert u.divide_denominator == ("xbrli:shares",)


def test_eps_fact_with_divide_unit(tmp_path):
    body = '<p>EPS: <ix:nonFraction name="us-gaap:EarningsPerShareDiluted" contextRef="c-duration" unitRef="usdPerShare" decimals="2" scale="0">2.90</ix:nonFraction></p>'
    xml = _build(_CONTEXT_DURATION + _UNIT_USD_PER_SHARE, body)
    root = _write_and_parse(tmp_path, xml)
    facts = extract_inline_facts(root)
    assert len(facts) == 1
    assert facts[0].normalized_value == Decimal("2.90")
    assert facts[0].unit_ref == "usdPerShare"


def test_annual_duration_maps_to_qtrs_4():
    from src.parse.inline_xbrl import XbrlContext, XbrlPeriod
    c = XbrlContext(context_id="x", entity_identifier="1", period=XbrlPeriod(period_type="duration", start_date="2023-01-01", end_date="2023-12-31"), dimensions=())
    period = context_to_truth_contract_period(c)
    assert period.ddate == "20231231"
    assert period.qtrs == 4


def test_quarterly_duration_maps_to_qtrs_1():
    from src.parse.inline_xbrl import XbrlContext, XbrlPeriod
    c = XbrlContext(context_id="x", entity_identifier="1", period=XbrlPeriod(period_type="duration", start_date="2023-10-01", end_date="2023-12-31"), dimensions=())
    period = context_to_truth_contract_period(c)
    assert period.ddate == "20231231"
    assert period.qtrs == 1


def test_instant_maps_to_qtrs_0():
    from src.parse.inline_xbrl import XbrlContext, XbrlPeriod
    c = XbrlContext(context_id="x", entity_identifier="1", period=XbrlPeriod(period_type="instant", instant="2023-12-31"), dimensions=())
    period = context_to_truth_contract_period(c)
    assert period.period_type == "instant"
    assert period.ddate == "20231231"
    assert period.qtrs == 0


# --------------------------------------------------------------- fact extraction (Section 69)

def test_paragraph_inline_fact(tmp_path):
    body = '<p>Revenue was <ix:nonFraction name="us-gaap:Revenues" contextRef="c-duration" unitRef="usd" decimals="-3" scale="3" format="ixt:num-dot-decimal">1,234</ix:nonFraction> thousand.</p>'
    xml = _build(_CONTEXT_DURATION + _UNIT_USD, body)
    root = _write_and_parse(tmp_path, xml)
    facts = extract_inline_facts(root)
    assert len(facts) == 1
    f = facts[0]
    assert f.fact_kind == "nonFraction"
    assert f.concept_qname == "us-gaap:Revenues"
    assert f.normalized_value == Decimal("1234000")


def test_table_cell_inline_fact(tmp_path):
    body = '<table><tr><td>Assets</td><td><ix:nonFraction name="us-gaap:Assets" contextRef="c-instant" unitRef="usd" decimals="-3" scale="3">5,000</ix:nonFraction></td></tr></table>'
    xml = _build(_CONTEXT_INSTANT + _UNIT_USD, body)
    root = _write_and_parse(tmp_path, xml)
    facts = extract_inline_facts(root)
    assert len(facts) == 1
    assert facts[0].normalized_value == Decimal("5000000")


def test_multiple_contexts_distinguished(tmp_path):
    body = (
        '<p><ix:nonFraction name="us-gaap:Revenues" contextRef="c-duration" unitRef="usd" decimals="-3" scale="0">100</ix:nonFraction></p>'
        '<p><ix:nonFraction name="us-gaap:Revenues" contextRef="c-quarter" unitRef="usd" decimals="-3" scale="0">25</ix:nonFraction></p>'
    )
    xml = _build(_CONTEXT_DURATION + _CONTEXT_QUARTER + _UNIT_USD, body)
    root = _write_and_parse(tmp_path, xml)
    facts = extract_inline_facts(root)
    assert len(facts) == 2
    by_context = {f.context_ref: f.normalized_value for f in facts}
    assert by_context["c-duration"] == Decimal("100")
    assert by_context["c-quarter"] == Decimal("25")


def test_same_fact_displayed_twice(tmp_path):
    body = (
        '<p>Summary: <ix:nonFraction name="us-gaap:Assets" contextRef="c-instant" unitRef="usd" decimals="-3" scale="0" id="f-1">5000</ix:nonFraction></p>'
        '<table><tr><td><ix:nonFraction name="us-gaap:Assets" contextRef="c-instant" unitRef="usd" decimals="-3" scale="0" id="f-2">5000</ix:nonFraction></td></tr></table>'
    )
    xml = _build(_CONTEXT_INSTANT + _UNIT_USD, body)
    root = _write_and_parse(tmp_path, xml)
    facts = extract_inline_facts(root)
    assert len(facts) == 2  # both occurrences preserved, never deduplicated (Section 44)
    assert {f.element_id for f in facts} == {"f-1", "f-2"}


def test_nil_fact_has_no_normalized_value(tmp_path):
    body = '<p><ix:nonFraction name="us-gaap:CommitmentsAndContingencies" contextRef="c-instant" unitRef="usd" xsi:nil="true"></ix:nonFraction></p>'
    xml = _build(_CONTEXT_INSTANT + _UNIT_USD, body)
    root = _write_and_parse(tmp_path, xml)
    facts = extract_inline_facts(root)
    assert len(facts) == 1
    assert facts[0].is_nil is True
    assert facts[0].normalized_value is None


def test_nonnumeric_text_fact(tmp_path):
    body = '<p><ix:nonNumeric name="dei:EntityRegistrantName" contextRef="c-instant">ACME CORP</ix:nonNumeric></p>'
    xml = _build(_CONTEXT_INSTANT, body)
    root = _write_and_parse(tmp_path, xml)
    facts = extract_inline_facts(root)
    assert len(facts) == 1
    assert facts[0].fact_kind == "nonNumeric"
    assert facts[0].raw_display_text == "ACME CORP"
    assert facts[0].normalized_value is None


def test_continuation_chain(tmp_path):
    body = (
        '<p><ix:nonNumeric name="dei:Description" contextRef="c-instant" id="start" continuedAt="cont-1">First part. </ix:nonNumeric></p>'
        '<p><ix:continuation id="cont-1">Second part.</ix:continuation></p>'
    )
    xml = _build(_CONTEXT_INSTANT, body)
    root = _write_and_parse(tmp_path, xml)
    facts = extract_inline_facts(root)
    assert len(facts) == 1
    assert facts[0].raw_display_text == "First part. Second part."


def test_continuation_chain_multi_hop(tmp_path):
    body = (
        '<p><ix:nonNumeric name="dei:Description" contextRef="c-instant" id="start" continuedAt="c1">A </ix:nonNumeric></p>'
        '<p><ix:continuation id="c1" continuedAt="c2">B </ix:continuation></p>'
        '<p><ix:continuation id="c2">C</ix:continuation></p>'
    )
    xml = _build(_CONTEXT_INSTANT, body)
    root = _write_and_parse(tmp_path, xml)
    facts = extract_inline_facts(root)
    assert facts[0].raw_display_text == "A B C"


def test_continuation_broken_chain_raises(tmp_path):
    body = '<p><ix:nonNumeric name="dei:Description" contextRef="c-instant" continuedAt="missing-id">A </ix:nonNumeric></p>'
    xml = _build(_CONTEXT_INSTANT, body)
    root = _write_and_parse(tmp_path, xml)
    with pytest.raises(InlineXbrlParseError):
        extract_inline_facts(root)


def test_malformed_but_recoverable_html(tmp_path):
    # unclosed <br> tag, common in real SEC filings - lxml's recover=True
    # should still parse the surrounding structure and the inline fact.
    body = '<p>Value: <br><ix:nonFraction name="us-gaap:Assets" contextRef="c-instant" unitRef="usd" decimals="-3" scale="0">100</ix:nonFraction></p>'
    xml = _build(_CONTEXT_INSTANT + _UNIT_USD, body)
    root = _write_and_parse(tmp_path, xml)
    facts = extract_inline_facts(root)
    assert len(facts) == 1
    assert facts[0].normalized_value == Decimal("100")


def test_case_sensitivity_preserved(tmp_path):
    # this is the exact bug found during real-data investigation:
    # lxml's HTMLParser would lowercase ix:nonFraction to ix:nonfraction
    # and silently extract 0 facts. Confirms XML parsing preserves case.
    body = '<p><ix:nonFraction name="us-gaap:Assets" contextRef="c-instant" unitRef="usd" decimals="-3" scale="0">1</ix:nonFraction></p>'
    xml = _build(_CONTEXT_INSTANT + _UNIT_USD, body)
    root = _write_and_parse(tmp_path, xml)
    facts = extract_inline_facts(root)
    assert len(facts) == 1
    assert facts[0].fact_kind == "nonFraction"


# --------------------------------------------------------------- local_data: real corpus validation

@pytest.mark.local_data
def test_numeric_normalization_matches_real_xbrl_fact():
    """Independent validation against a real data/xbrl.duckdb row - see
    module docstring. Never used to derive the normalization rule
    itself, only to confirm it after being written from the XBRL spec."""
    import duckdb
    from src.storage import get_storage
    from src.parse import inline_xbrl as ix

    storage = get_storage()
    path = storage.primary_docs_root / "100122" / "0000100122-24-000002.htm"
    if not path.exists():
        pytest.skip("real primary filing not present")

    root = ix.parse_xml(path)
    contexts = ix.extract_contexts(root)
    facts = ix.extract_inline_facts(root)
    revenues = [f for f in facts if f.concept_qname == "us-gaap:Revenues" and f.context_ref == "c-1"]
    assert revenues, "expected fact not found - real filing structure may have changed"
    fact = revenues[0]
    period = ix.context_to_truth_contract_period(contexts["c-1"])

    con = duckdb.connect(str(storage.repo_root / "data" / "xbrl.duckdb"), read_only=True)
    try:
        row = con.execute(
            "SELECT value FROM facts WHERE adsh=? AND tag='Revenues' AND ddate=? AND qtrs=? AND uom='USD' "
            "AND (coreg IS NULL OR coreg='') AND (segments IS NULL OR segments='')",
            ["0000100122-24-000002", period.ddate, period.qtrs],
        ).fetchone()
    finally:
        con.close()
    assert row is not None
    assert float(fact.normalized_value) == float(row[0])
